name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Или используемая версия Node.js

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Шаг 4: Экспорт всех секретов в переменные окружения
      - name: Export all secrets as env variables
        run: |
          echo '${{ toJson(secrets) }}' | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' >> $GITHUB_ENV

      # Шаг 5: Автоматическое создание .env-файла для Vue
      - name: Create .env file
        run: printenv | grep '^VUE_APP_' > .env

      # Шаг 6: Сборка проекта
      - name: Build project
        run: npm run build

      # Шаг 7: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
